<?php
/**
 * FuelEfficiency
 *
 * PHP version 5
 *
 * @category Class
 * @package  marketcheck\api\sdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketcheck Cars API
 *
 * <b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>
 *
 * OpenAPI spec version: 1.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace marketcheck\api\sdk\Model;

use \ArrayAccess;
use \marketcheck\api\sdk\ObjectSerializer;

/**
 * FuelEfficiency Class Doc Comment
 *
 * @category Class
 * @package  marketcheck\api\sdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class FuelEfficiency implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'FuelEfficiency';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'city_mileage' => 'string',
        'highway_mileage' => 'string',
        'combined_mileage' => 'string',
        'annual_miles' => 'float',
        'monthly_fuel_expense' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'city_mileage' => null,
        'highway_mileage' => null,
        'combined_mileage' => null,
        'annual_miles' => null,
        'monthly_fuel_expense' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'city_mileage' => 'city_mileage',
        'highway_mileage' => 'highway_mileage',
        'combined_mileage' => 'combined_mileage',
        'annual_miles' => 'annual_miles',
        'monthly_fuel_expense' => 'monthly_fuel_expense'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'city_mileage' => 'setCityMileage',
        'highway_mileage' => 'setHighwayMileage',
        'combined_mileage' => 'setCombinedMileage',
        'annual_miles' => 'setAnnualMiles',
        'monthly_fuel_expense' => 'setMonthlyFuelExpense'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'city_mileage' => 'getCityMileage',
        'highway_mileage' => 'getHighwayMileage',
        'combined_mileage' => 'getCombinedMileage',
        'annual_miles' => 'getAnnualMiles',
        'monthly_fuel_expense' => 'getMonthlyFuelExpense'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['city_mileage'] = isset($data['city_mileage']) ? $data['city_mileage'] : null;
        $this->container['highway_mileage'] = isset($data['highway_mileage']) ? $data['highway_mileage'] : null;
        $this->container['combined_mileage'] = isset($data['combined_mileage']) ? $data['combined_mileage'] : null;
        $this->container['annual_miles'] = isset($data['annual_miles']) ? $data['annual_miles'] : null;
        $this->container['monthly_fuel_expense'] = isset($data['monthly_fuel_expense']) ? $data['monthly_fuel_expense'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets city_mileage
     *
     * @return string
     */
    public function getCityMileage()
    {
        return $this->container['city_mileage'];
    }

    /**
     * Sets city_mileage
     *
     * @param string $city_mileage City Mileage in MPG
     *
     * @return $this
     */
    public function setCityMileage($city_mileage)
    {
        $this->container['city_mileage'] = $city_mileage;

        return $this;
    }

    /**
     * Gets highway_mileage
     *
     * @return string
     */
    public function getHighwayMileage()
    {
        return $this->container['highway_mileage'];
    }

    /**
     * Sets highway_mileage
     *
     * @param string $highway_mileage Highway Mileage in MPG
     *
     * @return $this
     */
    public function setHighwayMileage($highway_mileage)
    {
        $this->container['highway_mileage'] = $highway_mileage;

        return $this;
    }

    /**
     * Gets combined_mileage
     *
     * @return string
     */
    public function getCombinedMileage()
    {
        return $this->container['combined_mileage'];
    }

    /**
     * Sets combined_mileage
     *
     * @param string $combined_mileage Combined Mileage
     *
     * @return $this
     */
    public function setCombinedMileage($combined_mileage)
    {
        $this->container['combined_mileage'] = $combined_mileage;

        return $this;
    }

    /**
     * Gets annual_miles
     *
     * @return float
     */
    public function getAnnualMiles()
    {
        return $this->container['annual_miles'];
    }

    /**
     * Sets annual_miles
     *
     * @param float $annual_miles Annual Miles of Car
     *
     * @return $this
     */
    public function setAnnualMiles($annual_miles)
    {
        $this->container['annual_miles'] = $annual_miles;

        return $this;
    }

    /**
     * Gets monthly_fuel_expense
     *
     * @return float
     */
    public function getMonthlyFuelExpense()
    {
        return $this->container['monthly_fuel_expense'];
    }

    /**
     * Sets monthly_fuel_expense
     *
     * @param float $monthly_fuel_expense Monthly fuel expense
     *
     * @return $this
     */
    public function setMonthlyFuelExpense($monthly_fuel_expense)
    {
        $this->container['monthly_fuel_expense'] = $monthly_fuel_expense;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


