<?php
/**
 * BaseListingTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  marketcheck\api\sdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketcheck Cars API
 *
 * <b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>
 *
 * OpenAPI spec version: 1.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace marketcheck\api\sdk;

/**
 * BaseListingTest Class Doc Comment
 *
 * @category    Class
 * @description Minimal set of attributes describing a listing
 * @package     marketcheck\api\sdk
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BaseListingTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "BaseListing"
     */
    public function testBaseListing()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "heading"
     */
    public function testPropertyHeading()
    {
    }

    /**
     * Test attribute "vin"
     */
    public function testPropertyVin()
    {
    }

    /**
     * Test attribute "stock_no"
     */
    public function testPropertyStockNo()
    {
    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {
    }

    /**
     * Test attribute "miles"
     */
    public function testPropertyMiles()
    {
    }

    /**
     * Test attribute "inventory_type"
     */
    public function testPropertyInventoryType()
    {
    }

    /**
     * Test attribute "last_seen_at"
     */
    public function testPropertyLastSeenAt()
    {
    }

    /**
     * Test attribute "last_seen_at_date"
     */
    public function testPropertyLastSeenAtDate()
    {
    }

    /**
     * Test attribute "scraped_at_date"
     */
    public function testPropertyScrapedAtDate()
    {
    }

    /**
     * Test attribute "first_seen_at"
     */
    public function testPropertyFirstSeenAt()
    {
    }

    /**
     * Test attribute "first_seen_at_date"
     */
    public function testPropertyFirstSeenAtDate()
    {
    }

    /**
     * Test attribute "ref_price"
     */
    public function testPropertyRefPrice()
    {
    }

    /**
     * Test attribute "ref_miles"
     */
    public function testPropertyRefMiles()
    {
    }

    /**
     * Test attribute "ref_price_dt"
     */
    public function testPropertyRefPriceDt()
    {
    }

    /**
     * Test attribute "ref_miles_dt"
     */
    public function testPropertyRefMilesDt()
    {
    }

    /**
     * Test attribute "dom"
     */
    public function testPropertyDom()
    {
    }

    /**
     * Test attribute "dom_180"
     */
    public function testPropertyDom180()
    {
    }

    /**
     * Test attribute "dom_active"
     */
    public function testPropertyDomActive()
    {
    }

    /**
     * Test attribute "seller_type"
     */
    public function testPropertySellerType()
    {
    }

    /**
     * Test attribute "exterior_color"
     */
    public function testPropertyExteriorColor()
    {
    }

    /**
     * Test attribute "interior_color"
     */
    public function testPropertyInteriorColor()
    {
    }

    /**
     * Test attribute "vdp_url"
     */
    public function testPropertyVdpUrl()
    {
    }

    /**
     * Test attribute "carfax_1_owner"
     */
    public function testPropertyCarfax1Owner()
    {
    }

    /**
     * Test attribute "carfax_clean_title"
     */
    public function testPropertyCarfaxCleanTitle()
    {
    }

    /**
     * Test attribute "source"
     */
    public function testPropertySource()
    {
    }

    /**
     * Test attribute "financing_options"
     */
    public function testPropertyFinancingOptions()
    {
    }

    /**
     * Test attribute "leasing_options"
     */
    public function testPropertyLeasingOptions()
    {
    }

    /**
     * Test attribute "media"
     */
    public function testPropertyMedia()
    {
    }

    /**
     * Test attribute "build"
     */
    public function testPropertyBuild()
    {
    }

    /**
     * Test attribute "dealer"
     */
    public function testPropertyDealer()
    {
    }

    /**
     * Test attribute "is_certified"
     */
    public function testPropertyIsCertified()
    {
    }

    /**
     * Test attribute "distance"
     */
    public function testPropertyDistance()
    {
    }
}
