<?php
/**
 * CRMApiTest
 * PHP version 5
 *
 * @category Class
 * @package  marketcheck\api\sdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketcheck Cars API
 *
 * <b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>
 *
 * OpenAPI spec version: 1.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

require __DIR__.'/../../vendor/autoload.php';
require __DIR__.'/../../lib/Api/CRMApi.php';

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;

use \marketcheck\api\sdk\Configuration;
use \marketcheck\api\sdk\ApiException;
use \marketcheck\api\sdk\ObjectSerializer;

/**
 * CRMApiTest Class Doc Comment
 *
 * @category Class
 * @package  marketcheck\api\sdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CRMApiTest extends \PHPUnit_Framework_TestCase
{
    private $api_key = "your api key";
    private $vin = "1N4AA5AP8EC477345";
    private $sale_date = array(20180305,20180606);

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for crmCheck
     *
     * CRM check of a particular vin.
     *
     */
    public function testCrmCheck()
    {
        $apiInstance = new marketcheck\api\sdk\Api\CRMApi(new GuzzleHttp\Client());
        echo "\nShould return true for crm check as both dates match";
        try 
        {           
            $result = $apiInstance->crmCheck($this->vin, $this->sale_date[0], $this->api_key);
            $this->assertEquals(true, $result["for_sale"]);
            print_r("\n/v1/crm_check/$this->vin?api_key={{api_key}}&sale_date=".$this->sale_date[0].": endpoint working fine");
        } catch (Exception $e) {
            $this->fail($e->getMessage());
            }
        
        echo "\nShould return false for crm check";
        try 
        {           
            $result = $apiInstance->crmCheck($this->vin, $this->sale_date[1], $this->api_key);
            $this->assertEquals(false, $result["for_sale"]);
            print_r("\n/v1/crm_check/$this->vin?api_key={{api_key}}&sale_date=".$this->sale_date[1].": endpoint working fine");
        } catch (Exception $e) {
            $this->fail($e->getMessage());
            }
    }
}
