<?php
/**
 * DealerApiTest
 * PHP version 5
 *
 * @category Class
 * @package  marketcheck\api\sdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketcheck Cars API
 *
 * <b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>
 *
 * OpenAPI spec version: 1.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

require __DIR__.'/../../vendor/autoload.php';
require __DIR__.'/../../lib/Api/DealerApi.php';

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;

use \marketcheck\api\sdk\Configuration;
use \marketcheck\api\sdk\ApiException;
use \marketcheck\api\sdk\ObjectSerializer;

/**
 * DealerApiTest Class Doc Comment
 *
 * @category Class
 * @package  marketcheck\api\sdk
 * @author   Rajan Modi
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DealerApiTest extends \PHPUnit_Framework_TestCase
{
    private $dealer_id = array("1016810","1016017","1016710","1017138","1016732");
    private $api_key = "Your api key";  
    private $latitude;
    private $longitude;
    private $radius;
    private $rows;
    private $start;
    
    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for dealerSearch
     *
     * Find car dealers around.
     *
     */
    public function testDealerSearch()
    {
        $apiInstance = new marketcheck\api\sdk\Api\DealerApi(new GuzzleHttp\Client());
        // Radius array contains radius and expected dealer count
        $dummy_test_data = array
                            (  
                                array
                                (  
                                    "latitude" => 35, 
                                    "longitude" => -90,
                                    "radius" => array
                                                (
                                                    [20,126],
                                                    [30,228],
                                                    [50,255]
                                                )
                                ),
                                array
                                (  
                                    "latitude" => 40, 
                                    "longitude" => -80,
                                    "radius" => array
                                                (
                                                    [20,25],
                                                    [30,97],
                                                    [50,359]
                                                )
                                ),
                                array
                                (  
                                    "latitude" => 45, 
                                    "longitude" => -90,
                                    "radius" => array
                                                (
                                                    [20,3],
                                                    [30,34],
                                                    [50,74]
                                                ) 
                                )
                            );
        
        echo "\nValidating Dealers count";
        $limit = 10;
        foreach($dummy_test_data as $test_data)
        {
            foreach($test_data["radius"] as $dealer_data)    
            {   
                try 
                {    
                    $this->latitude = $test_data["latitude"];
                    $this->longitude = $test_data["longitude"];
                    $this->radius = $dealer_data[0];
                    $this->expected_dealer_count = $dealer_data[1];
                    $result = $apiInstance->dealerSearch($this->latitude, $this->longitude, $this->radius, $this->api_key);  
                    $lower_limit = $this->expected_dealer_count - (($limit * $this->expected_dealer_count)/100);
                    $upper_limit = $this->expected_dealer_count + (($limit * $this->expected_dealer_count)/100);
                    $api_dealer_cnt = $result["num_found"];
                    $this->assertGreaterThanOrEqual($lower_limit,$api_dealer_cnt);
                    $this->assertLessThanOrEqual($upper_limit,$api_dealer_cnt);                                 
                    print_r("\n/dealers?api_key={{api_key}}&latitude=$this->latitude&longitude=$this->longitude&radius=$this->radius: endpoint working fine");
                } catch (Exception $e) {
                    $this->fail($e->getMessage());
                    }
            }
        }
    }

    /**
     * Test case for getDealer
     *
     * Dealer by id.
     *
     */
    public function testGetDealer()
    {
        echo "\nValidating dealers on the basis of dealer id";
        $apiInstance = new marketcheck\api\sdk\Api\DealerApi(new GuzzleHttp\Client());
        foreach($this->dealer_id as $d_id) 
        {
            try 
            {
                $result = $apiInstance->getDealer($d_id, $this->api_key);
                $this->assertEquals($result["id"], $d_id);
                print_r("\n/dealer/$d_id?api_key={{api_key}}: endpoint working fine");
            } catch (Exception $e) {
                $this->fail($e->getMessage());
                }
        }
    }
}
