<?php
/**
 * HistoryApiTest
 * PHP version 5
 *
 * @category Class
 * @package  marketcheck\api\sdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketcheck Cars API
 *
 * <b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>
 *
 * OpenAPI spec version: 1.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

require __DIR__.'/../../vendor/autoload.php';
require __DIR__.'/../../lib/Api/HistoryApi.php';

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;

use \marketcheck\api\sdk\Configuration;
use \marketcheck\api\sdk\ApiException;
use \marketcheck\api\sdk\ObjectSerializer;

/**
 * HistoryApiTest Class Doc Comment
 *
 * @category Class
 * @package  marketcheck\api\sdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class HistoryApiTest extends \PHPUnit_Framework_TestCase
{
    private $api_key = "your api key";      
    private $vin; 
    private $fields = null; 
    private $rows = null; 
    private $page = null;

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for history
     *
     * Get a cars online listing history.
     *
     */
    public function testHistory()
    {
        $apiInstance = new marketcheck\api\sdk\Api\HistoryApi(new GuzzleHttp\Client());
        echo "\nTesting listing count for History api";       
        $this->vin = "1FTNE2CM2FKA81288";
        $this->fields = null; 
        $this->rows = null; 
        $this->page = null;
        
        try {
            $result = $apiInstance->history($this->vin, $this->api_key, $this->fields, $this->rows, $this->page);
            $count = 0;
             foreach($result as $listing)
                {
                $count = $count + 1;
                }
                $this->assertNotEquals($count, 0);            
                print_r("\n/history/$this->vin?api_key={{api_key}}: endpoint working fine");
               
            } catch (Exception $e) {
                print_r("\n/history/$this->vin?api_key={{api_key}}: No listing found");
                $this->fail($e->getMessage());
                }

        echo "\nTesting History api with fields";       
        $this->vin = "1FTNE2CM2FKA81288";
        $this->fields = "dealer_id,seller_name,vdp_url,source,last_seen_at,price,miles,city,state,zip,scraped_at"; 
        $this->rows = null; 
        $this->page = null;
        
        try {
            $result = $apiInstance->history($this->vin, $this->api_key, $this->fields, $this->rows, $this->page);
            $count = 0;
             foreach($result as $listing)
                {
                $count = $count + 1;  
                $this->assertArrayHasKey("seller_name", $listing);
                $this->assertArrayHasKey("dealer_id", $listing);
                $this->assertArrayHasKey("source", $listing);
                }
                $this->assertNotEquals($count, 0);                            
                print_r("\n/history/$this->vin?api_key={{api_key}}&fields=seller_type,dealer_id,seller_name,seller_phone,seller_email,vdp_url,source,last_seen_at,price,miles,city,state,zip,scraped_at: endpoint working fine");
               
            } catch (Exception $e) {
                $this->fail($e->getMessage());
                }
    }
}
