<?php
/**
 * MarketApiTest
 * PHP version 5
 *
 * @category Class
 * @package  marketcheck\api\sdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketcheck Cars API
 *
 * <b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>
 *
 * OpenAPI spec version: 1.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

require __DIR__.'/../../vendor/autoload.php';
require __DIR__.'/../../lib/Api/ListingsApi.php';

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;

use \marketcheck\api\sdk\Configuration;
use \marketcheck\api\sdk\ApiException;
use \marketcheck\api\sdk\ObjectSerializer;

/**
 * MarketApiTest Class Doc Comment
 *
 * @category Class
 * @package  marketcheck\api\sdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MarketApiTest extends \PHPUnit_Framework_TestCase
{
    private $api_key = "nbWPXNcG8V6EgOBsjejVQJd9A9zTerzG";
    private $vin = array("1FTNE2CM2FKA81288","1GYS4BKJ8FR290257","3GYFNBE3XFS537500","1FT7W2BT5FEA75059","1FMCU9J90FUA21186");
    private $latitude;
    private $longitude;
    private $radius;
    private $exact;
    private $start;
    private $debug;
    private $include_sold;
    private $year;
    private $make;
    private $model;
    private $trim;
    private $body_type;
    private $stats;

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getMDS
     *
     * Market Days Supply.
     *
     */
    public function testGetMDS()
    {
        $apiInstance = new marketcheck\api\sdk\Api\MarketApi(new GuzzleHttp\Client());
        $this->latitude = 37.998;
        $this->longitude = -84.522;
        $this->radius = 1000;
        $this->debug = "1";
        $this->exact = "true";
        $this->include_sold = null;
        
        foreach($this->vin as $h_vin) 
        {
            try {
                $result = $apiInstance->getMDS($this->vin, $this->api_key, $this->exact, $this->latitude, $this->longitude, $this->radius, $this->debug, $this->include_sold);
                //$this->assertNotEquals($result["mds"],'NULL');
                print_r($result);
                // $this->assertNotNull($result["mds"]);
                // $this->assertObjectHasAttribute((string)$result["year"], new stdClass);
                // $this->assertObjectHasAttribute($result["make"], new stdClass);
                // $this->assertObjectHasAttribute($result["model"], new stdClass);
                // $this->assertObjectHasAttribute($result["trim"], new stdClass);
                print_r("\n/mds?api_key={{api_key}}&vin=55SWF4JB8GU129288&latitude=37.998&longitude=-84.522&radius=1000&exact=true&debug=1: endpoint working fine");
                //todo   expect_json_keys([:year, :make, :model, :trim]) 
                } catch (Exception $e) {
                    $this->fail($e->getMessage());
                    }
        }
    }

    /**
     * Test case for getSalesCount
     *
     * Get sales count by make, model, year, trim or taxonomy vin.
     *
     */
    public function testGetSalesCount()
    {
    }
}
